package com.shop.web.entity;

public class CartExample extends Cart {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int userId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int sessionId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int goodsId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int goodsName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int goodsPrice_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int parentId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int isValid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    private int sysflag_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getUserId_Indicator() {
        return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setUserId_Indicator(int userId_Indicator) {
        this.userId_Indicator = userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getSessionId_Indicator() {
        return sessionId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setSessionId_Indicator(int sessionId_Indicator) {
        this.sessionId_Indicator = sessionId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getGoodsId_Indicator() {
        return goodsId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setGoodsId_Indicator(int goodsId_Indicator) {
        this.goodsId_Indicator = goodsId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getGoodsName_Indicator() {
        return goodsName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setGoodsName_Indicator(int goodsName_Indicator) {
        this.goodsName_Indicator = goodsName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getGoodsPrice_Indicator() {
        return goodsPrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setGoodsPrice_Indicator(int goodsPrice_Indicator) {
        this.goodsPrice_Indicator = goodsPrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getParentId_Indicator() {
        return parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setParentId_Indicator(int parentId_Indicator) {
        this.parentId_Indicator = parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getIsValid_Indicator() {
        return isValid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setIsValid_Indicator(int isValid_Indicator) {
        this.isValid_Indicator = isValid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public int getSysflag_Indicator() {
        return sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cart
     *
     * @abatorgenerated Sat Dec 17 22:21:46 CST 2011
     */
    public void setSysflag_Indicator(int sysflag_Indicator) {
        this.sysflag_Indicator = sysflag_Indicator;
    }
}