package com.shop.web.entity;

public class CategoryExample extends Category {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int name_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int description_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int parentId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int createTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int modifyTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int sysflag_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getName_Indicator() {
        return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setName_Indicator(int name_Indicator) {
        this.name_Indicator = name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getParentId_Indicator() {
        return parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setParentId_Indicator(int parentId_Indicator) {
        this.parentId_Indicator = parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getCreateTime_Indicator() {
        return createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setCreateTime_Indicator(int createTime_Indicator) {
        this.createTime_Indicator = createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getModifyTime_Indicator() {
        return modifyTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setModifyTime_Indicator(int modifyTime_Indicator) {
        this.modifyTime_Indicator = modifyTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getSysflag_Indicator() {
        return sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table category
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setSysflag_Indicator(int sysflag_Indicator) {
        this.sysflag_Indicator = sysflag_Indicator;
    }
}