package com.shop.web.entity;

public class GoodsImageExample extends GoodsImage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int goodsDetailId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int imageUrl_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int ismain_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int isvalid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private int sysflag_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getGoodsDetailId_Indicator() {
        return goodsDetailId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setGoodsDetailId_Indicator(int goodsDetailId_Indicator) {
        this.goodsDetailId_Indicator = goodsDetailId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getImageUrl_Indicator() {
        return imageUrl_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setImageUrl_Indicator(int imageUrl_Indicator) {
        this.imageUrl_Indicator = imageUrl_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getIsmain_Indicator() {
        return ismain_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setIsmain_Indicator(int ismain_Indicator) {
        this.ismain_Indicator = ismain_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getIsvalid_Indicator() {
        return isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setIsvalid_Indicator(int isvalid_Indicator) {
        this.isvalid_Indicator = isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int getSysflag_Indicator() {
        return sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setSysflag_Indicator(int sysflag_Indicator) {
        this.sysflag_Indicator = sysflag_Indicator;
    }
}