package com.shop.web.entity;

public class GoodsExample extends Goods {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int categroyId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int goodsName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int goodsNumber_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int goodsDesc_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int goodsPrice_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int promotePrice_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int createTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int sysflag_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    private int isvalid_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getCategroyId_Indicator() {
        return categroyId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setCategroyId_Indicator(int categroyId_Indicator) {
        this.categroyId_Indicator = categroyId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getGoodsName_Indicator() {
        return goodsName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setGoodsName_Indicator(int goodsName_Indicator) {
        this.goodsName_Indicator = goodsName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getGoodsNumber_Indicator() {
        return goodsNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setGoodsNumber_Indicator(int goodsNumber_Indicator) {
        this.goodsNumber_Indicator = goodsNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getGoodsDesc_Indicator() {
        return goodsDesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setGoodsDesc_Indicator(int goodsDesc_Indicator) {
        this.goodsDesc_Indicator = goodsDesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getGoodsPrice_Indicator() {
        return goodsPrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setGoodsPrice_Indicator(int goodsPrice_Indicator) {
        this.goodsPrice_Indicator = goodsPrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getPromotePrice_Indicator() {
        return promotePrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setPromotePrice_Indicator(int promotePrice_Indicator) {
        this.promotePrice_Indicator = promotePrice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getCreateTime_Indicator() {
        return createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setCreateTime_Indicator(int createTime_Indicator) {
        this.createTime_Indicator = createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getSysflag_Indicator() {
        return sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setSysflag_Indicator(int sysflag_Indicator) {
        this.sysflag_Indicator = sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public int getIsvalid_Indicator() {
        return isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    public void setIsvalid_Indicator(int isvalid_Indicator) {
        this.isvalid_Indicator = isvalid_Indicator;
    }
}