package com.shop.web.entity;

public class GoodsDetailExample extends GoodsDetail {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int goodsId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int goodsColor_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int goodsSize_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int isvalid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private int sysflag_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getGoodsId_Indicator() {
        return goodsId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsId_Indicator(int goodsId_Indicator) {
        this.goodsId_Indicator = goodsId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getGoodsColor_Indicator() {
        return goodsColor_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsColor_Indicator(int goodsColor_Indicator) {
        this.goodsColor_Indicator = goodsColor_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getGoodsSize_Indicator() {
        return goodsSize_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsSize_Indicator(int goodsSize_Indicator) {
        this.goodsSize_Indicator = goodsSize_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getIsvalid_Indicator() {
        return isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setIsvalid_Indicator(int isvalid_Indicator) {
        this.isvalid_Indicator = isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int getSysflag_Indicator() {
        return sysflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setSysflag_Indicator(int sysflag_Indicator) {
        this.sysflag_Indicator = sysflag_Indicator;
    }
}