package com.shop.web.entity;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
@XStreamAlias("Gdtlist")
public class GoodsDetail {
	
	private List<GoodsImage> goodsImage;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.goods_id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Integer goodsId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.goods_color
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private String goodsColor;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.goods_size
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private String goodsSize;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Byte isvalid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_detail.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Byte sysflag;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.Id
     *
     * @return the value of goods_detail.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.Id
     *
     * @param id the value for goods_detail.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.goods_id
     *
     * @return the value of goods_detail.goods_id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.goods_id
     *
     * @param goodsId the value for goods_detail.goods_id
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.goods_color
     *
     * @return the value of goods_detail.goods_color
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public String getGoodsColor() {
        return goodsColor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.goods_color
     *
     * @param goodsColor the value for goods_detail.goods_color
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsColor(String goodsColor) {
        this.goodsColor = goodsColor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.goods_size
     *
     * @return the value of goods_detail.goods_size
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.goods_size
     *
     * @param goodsSize the value for goods_detail.goods_size
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.isvalid
     *
     * @return the value of goods_detail.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.isvalid
     *
     * @param isvalid the value for goods_detail.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_detail.sysflag
     *
     * @return the value of goods_detail.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public Byte getSysflag() {
        return sysflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_detail.sysflag
     *
     * @param sysflag the value for goods_detail.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void setSysflag(Byte sysflag) {
        this.sysflag = sysflag;
    }

	public void setGoodsImage(List<GoodsImage> goodsImage) {
		this.goodsImage = goodsImage;
	}

	public List<GoodsImage> getGoodsImage() {
		return goodsImage;
	}
}