package com.shop.web.entity;

public class GoodsImage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.goods_detail_id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Long goodsDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.image_url
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private String imageUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.ismain
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Byte ismain;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Byte isvalid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods_image.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Byte sysflag;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.Id
     *
     * @return the value of goods_image.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.Id
     *
     * @param id the value for goods_image.Id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.goods_detail_id
     *
     * @return the value of goods_image.goods_detail_id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public Long getGoodsDetailId() {
        return goodsDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.goods_detail_id
     *
     * @param goodsDetailId the value for goods_image.goods_detail_id
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setGoodsDetailId(Long goodsDetailId) {
        this.goodsDetailId = goodsDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.image_url
     *
     * @return the value of goods_image.image_url
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.image_url
     *
     * @param imageUrl the value for goods_image.image_url
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.ismain
     *
     * @return the value of goods_image.ismain
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public Byte getIsmain() {
        return ismain;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.ismain
     *
     * @param ismain the value for goods_image.ismain
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setIsmain(Byte ismain) {
        this.ismain = ismain;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.isvalid
     *
     * @return the value of goods_image.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.isvalid
     *
     * @param isvalid the value for goods_image.isvalid
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods_image.sysflag
     *
     * @return the value of goods_image.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public Byte getSysflag() {
        return sysflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods_image.sysflag
     *
     * @param sysflag the value for goods_image.sysflag
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public void setSysflag(Byte sysflag) {
        this.sysflag = sysflag;
    }
}