package com.shop.web.entity;

public class OrdersExample extends Orders {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int orderId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int orderStatus_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int userid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int address_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int telphone_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int payTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int email_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int orderGoods_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private int flag_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getOrderId_Indicator() {
        return orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderId_Indicator(int orderId_Indicator) {
        this.orderId_Indicator = orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getOrderStatus_Indicator() {
        return orderStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderStatus_Indicator(int orderStatus_Indicator) {
        this.orderStatus_Indicator = orderStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getUserid_Indicator() {
        return userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setUserid_Indicator(int userid_Indicator) {
        this.userid_Indicator = userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getAddress_Indicator() {
        return address_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setAddress_Indicator(int address_Indicator) {
        this.address_Indicator = address_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getTelphone_Indicator() {
        return telphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setTelphone_Indicator(int telphone_Indicator) {
        this.telphone_Indicator = telphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getPayTime_Indicator() {
        return payTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setPayTime_Indicator(int payTime_Indicator) {
        this.payTime_Indicator = payTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getEmail_Indicator() {
        return email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setEmail_Indicator(int email_Indicator) {
        this.email_Indicator = email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getOrderGoods_Indicator() {
        return orderGoods_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderGoods_Indicator(int orderGoods_Indicator) {
        this.orderGoods_Indicator = orderGoods_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int getFlag_Indicator() {
        return flag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setFlag_Indicator(int flag_Indicator) {
        this.flag_Indicator = flag_Indicator;
    }
}