package com.shop.web.entity;

public class OrderGoods {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.categroy_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Integer categroyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_name
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String goodsName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_number
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String goodsNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_desc
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String goodsDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Integer goodsPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.promote_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String promotePrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.create_time
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Long createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_color
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String goodsColor;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.goods_size
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String goodsSize;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_goods.flag
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Byte flag;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.Id
     *
     * @return the value of order_goods.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.Id
     *
     * @param id the value for order_goods.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.categroy_id
     *
     * @return the value of order_goods.categroy_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Integer getCategroyId() {
        return categroyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.categroy_id
     *
     * @param categroyId the value for order_goods.categroy_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCategroyId(Integer categroyId) {
        this.categroyId = categroyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_name
     *
     * @return the value of order_goods.goods_name
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_name
     *
     * @param goodsName the value for order_goods.goods_name
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_number
     *
     * @return the value of order_goods.goods_number
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_number
     *
     * @param goodsNumber the value for order_goods.goods_number
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsNumber(String goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_desc
     *
     * @return the value of order_goods.goods_desc
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_desc
     *
     * @param goodsDesc the value for order_goods.goods_desc
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_price
     *
     * @return the value of order_goods.goods_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_price
     *
     * @param goodsPrice the value for order_goods.goods_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.promote_price
     *
     * @return the value of order_goods.promote_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.promote_price
     *
     * @param promotePrice the value for order_goods.promote_price
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setPromotePrice(String promotePrice) {
        this.promotePrice = promotePrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.create_time
     *
     * @return the value of order_goods.create_time
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.create_time
     *
     * @param createTime the value for order_goods.create_time
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_color
     *
     * @return the value of order_goods.goods_color
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getGoodsColor() {
        return goodsColor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_color
     *
     * @param goodsColor the value for order_goods.goods_color
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsColor(String goodsColor) {
        this.goodsColor = goodsColor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.goods_size
     *
     * @return the value of order_goods.goods_size
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.goods_size
     *
     * @param goodsSize the value for order_goods.goods_size
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_goods.flag
     *
     * @return the value of order_goods.flag
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_goods.flag
     *
     * @param flag the value for order_goods.flag
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}