package com.shop.web.entity;

public class Orders {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.Id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.order_id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private String orderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.order_status
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private String orderStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.userid
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Long userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.address
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.telphone
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private String telphone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.pay_time
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Long payTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.email
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.order_goods
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Long orderGoods;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column orders.flag
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Byte flag;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.Id
     *
     * @return the value of orders.Id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.Id
     *
     * @param id the value for orders.Id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.userid
     *
     * @return the value of orders.userid
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.userid
     *
     * @param userid the value for orders.userid
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.telphone
     *
     * @return the value of orders.telphone
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.telphone
     *
     * @param telphone the value for orders.telphone
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.pay_time
     *
     * @return the value of orders.pay_time
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.pay_time
     *
     * @param payTime the value for orders.pay_time
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.email
     *
     * @return the value of orders.email
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.email
     *
     * @param email the value for orders.email
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.order_goods
     *
     * @return the value of orders.order_goods
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Long getOrderGoods() {
        return orderGoods;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.order_goods
     *
     * @param orderGoods the value for orders.order_goods
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setOrderGoods(Long orderGoods) {
        this.orderGoods = orderGoods;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column orders.flag
     *
     * @return the value of orders.flag
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column orders.flag
     *
     * @param flag the value for orders.flag
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}