package com.shop.web.entity;

public class UserAddressExample extends UserAddress {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int userId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int province_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int city_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int country_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int addr_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int telphone_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int email_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int isdefault_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private int isvalid_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getUserId_Indicator() {
        return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setUserId_Indicator(int userId_Indicator) {
        this.userId_Indicator = userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getProvince_Indicator() {
        return province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setProvince_Indicator(int province_Indicator) {
        this.province_Indicator = province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getCity_Indicator() {
        return city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCity_Indicator(int city_Indicator) {
        this.city_Indicator = city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getCountry_Indicator() {
        return country_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCountry_Indicator(int country_Indicator) {
        this.country_Indicator = country_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getAddr_Indicator() {
        return addr_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setAddr_Indicator(int addr_Indicator) {
        this.addr_Indicator = addr_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getTelphone_Indicator() {
        return telphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setTelphone_Indicator(int telphone_Indicator) {
        this.telphone_Indicator = telphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getEmail_Indicator() {
        return email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setEmail_Indicator(int email_Indicator) {
        this.email_Indicator = email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getIsdefault_Indicator() {
        return isdefault_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setIsdefault_Indicator(int isdefault_Indicator) {
        this.isdefault_Indicator = isdefault_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int getIsvalid_Indicator() {
        return isvalid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setIsvalid_Indicator(int isvalid_Indicator) {
        this.isvalid_Indicator = isvalid_Indicator;
    }
}