package com.shop.web.entity;

public class UserAddress {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.user_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Long userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.province
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String province;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.city
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.country
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String country;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.addr
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String addr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.telphone
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String telphone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.email
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.isdefault
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Byte isdefault;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_address.isvalid
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Byte isvalid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.Id
     *
     * @return the value of user_address.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.Id
     *
     * @param id the value for user_address.Id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.province
     *
     * @return the value of user_address.province
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.province
     *
     * @param province the value for user_address.province
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.city
     *
     * @return the value of user_address.city
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.city
     *
     * @param city the value for user_address.city
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.country
     *
     * @return the value of user_address.country
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.country
     *
     * @param country the value for user_address.country
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.addr
     *
     * @return the value of user_address.addr
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.addr
     *
     * @param addr the value for user_address.addr
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.telphone
     *
     * @return the value of user_address.telphone
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.telphone
     *
     * @param telphone the value for user_address.telphone
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.email
     *
     * @return the value of user_address.email
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.email
     *
     * @param email the value for user_address.email
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.isdefault
     *
     * @return the value of user_address.isdefault
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Byte getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.isdefault
     *
     * @param isdefault the value for user_address.isdefault
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setIsdefault(Byte isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_address.isvalid
     *
     * @return the value of user_address.isvalid
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_address.isvalid
     *
     * @param isvalid the value for user_address.isvalid
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }
}