package com.shop.web.dao;

import com.shop.web.entity.GoodsImage;
import com.shop.web.entity.GoodsImageExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodsImageDAOImpl extends SqlMapClientDaoSupport implements GoodsImageDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public GoodsImageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int insert(GoodsImage record) {
        return ((Integer) getSqlMapClientTemplate().insert("goods_image.abatorgenerated_insert", record)).intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int updateByPrimaryKey(GoodsImage record) {
        int rows = getSqlMapClientTemplate().update("goods_image.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int updateByPrimaryKeySelective(GoodsImage record) {
        int rows = getSqlMapClientTemplate().update("goods_image.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public List selectByExample(GoodsImageExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("goods_image.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public List selectByExample(GoodsImageExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public GoodsImage selectByPrimaryKey(Integer id) {
        GoodsImage key = new GoodsImage();
        key.setId(id);
        GoodsImage record = (GoodsImage) getSqlMapClientTemplate().queryForObject("goods_image.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int deleteByExample(GoodsImageExample example) {
        int rows = getSqlMapClientTemplate().delete("goods_image.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        GoodsImage key = new GoodsImage();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("goods_image.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getIdExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NULL", "Y");
            } else {
                parms.put("AND_Id_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_NULL", "Y");
            } else {
                parms.put("AND_Id_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_EQUALS", "Y");
            } else {
                parms.put("AND_Id_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_Id_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GT", "Y");
            } else {
                parms.put("AND_Id_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GE", "Y");
            } else {
                parms.put("AND_Id_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LT", "Y");
            } else {
                parms.put("AND_Id_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LE", "Y");
            } else {
                parms.put("AND_Id_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getgoods_detail_idExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsDetailId_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_NULL", "Y");
            } else {
                parms.put("AND_goods_detail_id_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_detail_id_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_EQUALS", "Y");
            } else {
                parms.put("AND_goods_detail_id_EQUALS", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_detail_id_NOT_EQUALS", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_GT", "Y");
            } else {
                parms.put("AND_goods_detail_id_GT", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_GE", "Y");
            } else {
                parms.put("AND_goods_detail_id_GE", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_LT", "Y");
            } else {
                parms.put("AND_goods_detail_id_LT", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_detail_id_LE", "Y");
            } else {
                parms.put("AND_goods_detail_id_LE", "Y");
            }
            parms.put("goodsDetailId", example.getGoodsDetailId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getimage_urlExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getImageUrl_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_NULL", "Y");
            } else {
                parms.put("AND_image_url_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_NOT_NULL", "Y");
            } else {
                parms.put("AND_image_url_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_EQUALS", "Y");
            } else {
                parms.put("AND_image_url_EQUALS", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_image_url_NOT_EQUALS", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_GT", "Y");
            } else {
                parms.put("AND_image_url_GT", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_GE", "Y");
            } else {
                parms.put("AND_image_url_GE", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_LT", "Y");
            } else {
                parms.put("AND_image_url_LT", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_LE", "Y");
            } else {
                parms.put("AND_image_url_LE", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        case GoodsImageExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_image_url_LIKE", "Y");
            } else {
                parms.put("AND_image_url_LIKE", "Y");
            }
            parms.put("imageUrl", example.getImageUrl());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getismainExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getIsmain_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_NULL", "Y");
            } else {
                parms.put("AND_ismain_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_NOT_NULL", "Y");
            } else {
                parms.put("AND_ismain_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_EQUALS", "Y");
            } else {
                parms.put("AND_ismain_EQUALS", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ismain_NOT_EQUALS", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_GT", "Y");
            } else {
                parms.put("AND_ismain_GT", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_GE", "Y");
            } else {
                parms.put("AND_ismain_GE", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_LT", "Y");
            } else {
                parms.put("AND_ismain_LT", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ismain_LE", "Y");
            } else {
                parms.put("AND_ismain_LE", "Y");
            }
            parms.put("ismain", example.getIsmain());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getisvalidExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getIsvalid_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NULL", "Y");
            } else {
                parms.put("AND_isvalid_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NOT_NULL", "Y");
            } else {
                parms.put("AND_isvalid_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_EQUALS", "Y");
            } else {
                parms.put("AND_isvalid_EQUALS", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_isvalid_NOT_EQUALS", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_GT", "Y");
            } else {
                parms.put("AND_isvalid_GT", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_GE", "Y");
            } else {
                parms.put("AND_isvalid_GE", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_LT", "Y");
            } else {
                parms.put("AND_isvalid_LT", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_LE", "Y");
            } else {
                parms.put("AND_isvalid_LE", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getsysflagExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        switch (example.getSysflag_Indicator()) {
        case GoodsImageExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NOT_NULL", "Y");
            }
            break;
        case GoodsImageExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsImageExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_NOT_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GT", "Y");
            } else {
                parms.put("AND_sysflag_GT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsImageExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GE", "Y");
            } else {
                parms.put("AND_sysflag_GE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LT", "Y");
            } else {
                parms.put("AND_sysflag_LT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsImageExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LE", "Y");
            } else {
                parms.put("AND_sysflag_LE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    private Map getExampleParms(GoodsImageExample example) {
        Map parms = new HashMap();
        parms.putAll(getIdExampleParms(example));
        parms.putAll(getgoods_detail_idExampleParms(example));
        parms.putAll(getimage_urlExampleParms(example));
        parms.putAll(getismainExampleParms(example));
        parms.putAll(getisvalidExampleParms(example));
        parms.putAll(getsysflagExampleParms(example));
        return parms;
    }
}