package com.shop.web.dao;

import com.shop.web.entity.GoodsDetail;
import com.shop.web.entity.GoodsDetailExample;
import com.shop.web.vo.GoodsVo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodsDetailDAOImpl extends SqlMapClientDaoSupport implements GoodsDetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public GoodsDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int insert(GoodsDetail record) {
        return ((Integer) getSqlMapClientTemplate().insert("goods_detail.abatorgenerated_insert", record)).intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int updateByPrimaryKey(GoodsDetail record) {
        int rows = getSqlMapClientTemplate().update("goods_detail.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int updateByPrimaryKeySelective(GoodsDetail record) {
        int rows = getSqlMapClientTemplate().update("goods_detail.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public List selectByExample(GoodsDetailExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("goods_detail.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public List selectByExample(GoodsDetailExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public GoodsDetail selectByPrimaryKey(Integer id) {
        GoodsDetail key = new GoodsDetail();
        key.setId(id);
        GoodsDetail record = (GoodsDetail) getSqlMapClientTemplate().queryForObject("goods_detail.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int deleteByExample(GoodsDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("goods_detail.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        GoodsDetail key = new GoodsDetail();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("goods_detail.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getIdExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NULL", "Y");
            } else {
                parms.put("AND_Id_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_NULL", "Y");
            } else {
                parms.put("AND_Id_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_EQUALS", "Y");
            } else {
                parms.put("AND_Id_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_Id_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GT", "Y");
            } else {
                parms.put("AND_Id_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GE", "Y");
            } else {
                parms.put("AND_Id_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LT", "Y");
            } else {
                parms.put("AND_Id_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LE", "Y");
            } else {
                parms.put("AND_Id_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getgoods_idExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsId_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_NULL", "Y");
            } else {
                parms.put("AND_goods_id_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_id_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_EQUALS", "Y");
            } else {
                parms.put("AND_goods_id_EQUALS", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_id_NOT_EQUALS", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_GT", "Y");
            } else {
                parms.put("AND_goods_id_GT", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_GE", "Y");
            } else {
                parms.put("AND_goods_id_GE", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_LT", "Y");
            } else {
                parms.put("AND_goods_id_LT", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_id_LE", "Y");
            } else {
                parms.put("AND_goods_id_LE", "Y");
            }
            parms.put("goodsId", example.getGoodsId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getgoods_colorExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsColor_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NULL", "Y");
            } else {
                parms.put("AND_goods_color_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_color_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_EQUALS", "Y");
            } else {
                parms.put("AND_goods_color_EQUALS", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_color_NOT_EQUALS", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_GT", "Y");
            } else {
                parms.put("AND_goods_color_GT", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_GE", "Y");
            } else {
                parms.put("AND_goods_color_GE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LT", "Y");
            } else {
                parms.put("AND_goods_color_LT", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LE", "Y");
            } else {
                parms.put("AND_goods_color_LE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case GoodsDetailExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LIKE", "Y");
            } else {
                parms.put("AND_goods_color_LIKE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getgoods_sizeExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsSize_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NULL", "Y");
            } else {
                parms.put("AND_goods_size_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_size_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_EQUALS", "Y");
            } else {
                parms.put("AND_goods_size_EQUALS", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_size_NOT_EQUALS", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_GT", "Y");
            } else {
                parms.put("AND_goods_size_GT", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_GE", "Y");
            } else {
                parms.put("AND_goods_size_GE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LT", "Y");
            } else {
                parms.put("AND_goods_size_LT", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LE", "Y");
            } else {
                parms.put("AND_goods_size_LE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case GoodsDetailExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LIKE", "Y");
            } else {
                parms.put("AND_goods_size_LIKE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getisvalidExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getIsvalid_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NULL", "Y");
            } else {
                parms.put("AND_isvalid_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NOT_NULL", "Y");
            } else {
                parms.put("AND_isvalid_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_EQUALS", "Y");
            } else {
                parms.put("AND_isvalid_EQUALS", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_isvalid_NOT_EQUALS", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_GT", "Y");
            } else {
                parms.put("AND_isvalid_GT", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_GE", "Y");
            } else {
                parms.put("AND_isvalid_GE", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_LT", "Y");
            } else {
                parms.put("AND_isvalid_LT", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_isvalid_LE", "Y");
            } else {
                parms.put("AND_isvalid_LE", "Y");
            }
            parms.put("isvalid", example.getIsvalid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getsysflagExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        switch (example.getSysflag_Indicator()) {
        case GoodsDetailExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NOT_NULL", "Y");
            }
            break;
        case GoodsDetailExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsDetailExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_NOT_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GT", "Y");
            } else {
                parms.put("AND_sysflag_GT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsDetailExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GE", "Y");
            } else {
                parms.put("AND_sysflag_GE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LT", "Y");
            } else {
                parms.put("AND_sysflag_LT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case GoodsDetailExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LE", "Y");
            } else {
                parms.put("AND_sysflag_LE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getExampleParms(GoodsDetailExample example) {
        Map parms = new HashMap();
        parms.putAll(getIdExampleParms(example));
        parms.putAll(getgoods_idExampleParms(example));
        parms.putAll(getgoods_colorExampleParms(example));
        parms.putAll(getgoods_sizeExampleParms(example));
        parms.putAll(getisvalidExampleParms(example));
        parms.putAll(getsysflagExampleParms(example));
        return parms;
    }

	@Override
	public GoodsVo getGoodVoByDetailId(int id) {
		// TODO Auto-generated method stub
		GoodsVo goodsVo=(GoodsVo)getSqlMapClientTemplate().queryForObject("goods_detail.selectGoodsVoByDetailId", id);
		
		return goodsVo;
	}
}