package com.shop.web.dao;

import com.shop.web.entity.GoodsDetail;
import com.shop.web.entity.GoodsDetailExample;
import com.shop.web.vo.GoodsVo;

import java.util.List;

public interface GoodsDetailDAO {
	
	GoodsVo getGoodVoByDetailId(int id);
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    int insert(GoodsDetail record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    int updateByPrimaryKey(GoodsDetail record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    int updateByPrimaryKeySelective(GoodsDetail record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    List selectByExample(GoodsDetailExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    List selectByExample(GoodsDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    GoodsDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    int deleteByExample(GoodsDetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_detail
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    int deleteByPrimaryKey(Integer id);
}