package com.shop.web.dao;

import com.shop.web.entity.GoodsImage;
import com.shop.web.entity.GoodsImageExample;
import java.util.List;

public interface GoodsImageDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    int insert(GoodsImage record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    int updateByPrimaryKey(GoodsImage record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    int updateByPrimaryKeySelective(GoodsImage record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    List selectByExample(GoodsImageExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    List selectByExample(GoodsImageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    GoodsImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    int deleteByExample(GoodsImageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods_image
     *
     * @abatorgenerated Sat Dec 17 22:21:49 CST 2011
     */
    int deleteByPrimaryKey(Integer id);
}