package com.shop.web.dao;

import com.shop.web.entity.Goods;
import com.shop.web.entity.GoodsExample;

import java.util.HashMap;
import java.util.List;

public interface GoodsDAO {
	
	public List<Goods>getGoodsList(int catid);
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    int insert(Goods record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    int updateByPrimaryKey(Goods record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    List selectByExample(GoodsExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    List selectByExample(GoodsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table goods
     *
     * @abatorgenerated Sat Dec 17 22:21:47 CST 2011
     */
    int deleteByPrimaryKey(Integer id);
	public int findCountByExample(GoodsExample inparam);
	List<?> findListByExample(HashMap<String, Object> param);
}