package com.shop.web.dao;

import com.shop.web.entity.OrderGoods;
import com.shop.web.entity.OrderGoodsExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderGoodsDAOImpl extends SqlMapClientDaoSupport implements OrderGoodsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public OrderGoodsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int insert(OrderGoods record) {
    	return (Integer) getSqlMapClientTemplate().insert("order_goods.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int updateByPrimaryKey(OrderGoods record) {
        int rows = getSqlMapClientTemplate().update("order_goods.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int updateByPrimaryKeySelective(OrderGoods record) {
        int rows = getSqlMapClientTemplate().update("order_goods.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public List selectByExample(OrderGoodsExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("order_goods.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public List selectByExample(OrderGoodsExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public OrderGoods selectByPrimaryKey(Integer id) {
        OrderGoods key = new OrderGoods();
        key.setId(id);
        OrderGoods record = (OrderGoods) getSqlMapClientTemplate().queryForObject("order_goods.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int deleteByExample(OrderGoodsExample example) {
        int rows = getSqlMapClientTemplate().delete("order_goods.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        OrderGoods key = new OrderGoods();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("order_goods.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getIdExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NULL", "Y");
            } else {
                parms.put("AND_Id_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_NULL", "Y");
            } else {
                parms.put("AND_Id_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_EQUALS", "Y");
            } else {
                parms.put("AND_Id_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_Id_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GT", "Y");
            } else {
                parms.put("AND_Id_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GE", "Y");
            } else {
                parms.put("AND_Id_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LT", "Y");
            } else {
                parms.put("AND_Id_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LE", "Y");
            } else {
                parms.put("AND_Id_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getcategroy_idExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getCategroyId_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_NULL", "Y");
            } else {
                parms.put("AND_categroy_id_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_NOT_NULL", "Y");
            } else {
                parms.put("AND_categroy_id_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_EQUALS", "Y");
            } else {
                parms.put("AND_categroy_id_EQUALS", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_categroy_id_NOT_EQUALS", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_GT", "Y");
            } else {
                parms.put("AND_categroy_id_GT", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_GE", "Y");
            } else {
                parms.put("AND_categroy_id_GE", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_LT", "Y");
            } else {
                parms.put("AND_categroy_id_LT", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_categroy_id_LE", "Y");
            } else {
                parms.put("AND_categroy_id_LE", "Y");
            }
            parms.put("categroyId", example.getCategroyId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_nameExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsName_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_NULL", "Y");
            } else {
                parms.put("AND_goods_name_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_name_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_EQUALS", "Y");
            } else {
                parms.put("AND_goods_name_EQUALS", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_name_NOT_EQUALS", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_GT", "Y");
            } else {
                parms.put("AND_goods_name_GT", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_GE", "Y");
            } else {
                parms.put("AND_goods_name_GE", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_LT", "Y");
            } else {
                parms.put("AND_goods_name_LT", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_LE", "Y");
            } else {
                parms.put("AND_goods_name_LE", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_name_LIKE", "Y");
            } else {
                parms.put("AND_goods_name_LIKE", "Y");
            }
            parms.put("goodsName", example.getGoodsName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_numberExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsNumber_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_NULL", "Y");
            } else {
                parms.put("AND_goods_number_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_number_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_EQUALS", "Y");
            } else {
                parms.put("AND_goods_number_EQUALS", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_number_NOT_EQUALS", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_GT", "Y");
            } else {
                parms.put("AND_goods_number_GT", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_GE", "Y");
            } else {
                parms.put("AND_goods_number_GE", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_LT", "Y");
            } else {
                parms.put("AND_goods_number_LT", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_LE", "Y");
            } else {
                parms.put("AND_goods_number_LE", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_number_LIKE", "Y");
            } else {
                parms.put("AND_goods_number_LIKE", "Y");
            }
            parms.put("goodsNumber", example.getGoodsNumber());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_descExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsDesc_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_NULL", "Y");
            } else {
                parms.put("AND_goods_desc_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_desc_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_EQUALS", "Y");
            } else {
                parms.put("AND_goods_desc_EQUALS", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_desc_NOT_EQUALS", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_GT", "Y");
            } else {
                parms.put("AND_goods_desc_GT", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_GE", "Y");
            } else {
                parms.put("AND_goods_desc_GE", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_LT", "Y");
            } else {
                parms.put("AND_goods_desc_LT", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_LE", "Y");
            } else {
                parms.put("AND_goods_desc_LE", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_desc_LIKE", "Y");
            } else {
                parms.put("AND_goods_desc_LIKE", "Y");
            }
            parms.put("goodsDesc", example.getGoodsDesc());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_priceExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsPrice_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_NULL", "Y");
            } else {
                parms.put("AND_goods_price_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_price_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_EQUALS", "Y");
            } else {
                parms.put("AND_goods_price_EQUALS", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_price_NOT_EQUALS", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_GT", "Y");
            } else {
                parms.put("AND_goods_price_GT", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_GE", "Y");
            } else {
                parms.put("AND_goods_price_GE", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_LT", "Y");
            } else {
                parms.put("AND_goods_price_LT", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_price_LE", "Y");
            } else {
                parms.put("AND_goods_price_LE", "Y");
            }
            parms.put("goodsPrice", example.getGoodsPrice());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getpromote_priceExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getPromotePrice_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_NULL", "Y");
            } else {
                parms.put("AND_promote_price_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_NOT_NULL", "Y");
            } else {
                parms.put("AND_promote_price_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_EQUALS", "Y");
            } else {
                parms.put("AND_promote_price_EQUALS", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_promote_price_NOT_EQUALS", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_GT", "Y");
            } else {
                parms.put("AND_promote_price_GT", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_GE", "Y");
            } else {
                parms.put("AND_promote_price_GE", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_LT", "Y");
            } else {
                parms.put("AND_promote_price_LT", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_LE", "Y");
            } else {
                parms.put("AND_promote_price_LE", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_promote_price_LIKE", "Y");
            } else {
                parms.put("AND_promote_price_LIKE", "Y");
            }
            parms.put("promotePrice", example.getPromotePrice());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getcreate_timeExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getCreateTime_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_NULL", "Y");
            } else {
                parms.put("AND_create_time_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_NOT_NULL", "Y");
            } else {
                parms.put("AND_create_time_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_EQUALS", "Y");
            } else {
                parms.put("AND_create_time_EQUALS", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_create_time_NOT_EQUALS", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_GT", "Y");
            } else {
                parms.put("AND_create_time_GT", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_GE", "Y");
            } else {
                parms.put("AND_create_time_GE", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_LT", "Y");
            } else {
                parms.put("AND_create_time_LT", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_create_time_LE", "Y");
            } else {
                parms.put("AND_create_time_LE", "Y");
            }
            parms.put("createTime", example.getCreateTime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_colorExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsColor_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NULL", "Y");
            } else {
                parms.put("AND_goods_color_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_color_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_EQUALS", "Y");
            } else {
                parms.put("AND_goods_color_EQUALS", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_color_NOT_EQUALS", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_GT", "Y");
            } else {
                parms.put("AND_goods_color_GT", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_GE", "Y");
            } else {
                parms.put("AND_goods_color_GE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LT", "Y");
            } else {
                parms.put("AND_goods_color_LT", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LE", "Y");
            } else {
                parms.put("AND_goods_color_LE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_color_LIKE", "Y");
            } else {
                parms.put("AND_goods_color_LIKE", "Y");
            }
            parms.put("goodsColor", example.getGoodsColor());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getgoods_sizeExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getGoodsSize_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NULL", "Y");
            } else {
                parms.put("AND_goods_size_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NOT_NULL", "Y");
            } else {
                parms.put("AND_goods_size_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_EQUALS", "Y");
            } else {
                parms.put("AND_goods_size_EQUALS", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_goods_size_NOT_EQUALS", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_GT", "Y");
            } else {
                parms.put("AND_goods_size_GT", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_GE", "Y");
            } else {
                parms.put("AND_goods_size_GE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LT", "Y");
            } else {
                parms.put("AND_goods_size_LT", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LE", "Y");
            } else {
                parms.put("AND_goods_size_LE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        case OrderGoodsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_goods_size_LIKE", "Y");
            } else {
                parms.put("AND_goods_size_LIKE", "Y");
            }
            parms.put("goodsSize", example.getGoodsSize());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getflagExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        switch (example.getFlag_Indicator()) {
        case OrderGoodsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NULL", "Y");
            } else {
                parms.put("AND_flag_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NOT_NULL", "Y");
            } else {
                parms.put("AND_flag_NOT_NULL", "Y");
            }
            break;
        case OrderGoodsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_EQUALS", "Y");
            } else {
                parms.put("AND_flag_EQUALS", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrderGoodsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_flag_NOT_EQUALS", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_GT", "Y");
            } else {
                parms.put("AND_flag_GT", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrderGoodsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_GE", "Y");
            } else {
                parms.put("AND_flag_GE", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_LT", "Y");
            } else {
                parms.put("AND_flag_LT", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrderGoodsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_LE", "Y");
            } else {
                parms.put("AND_flag_LE", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_goods
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    private Map getExampleParms(OrderGoodsExample example) {
        Map parms = new HashMap();
        parms.putAll(getIdExampleParms(example));
        parms.putAll(getcategroy_idExampleParms(example));
        parms.putAll(getgoods_nameExampleParms(example));
        parms.putAll(getgoods_numberExampleParms(example));
        parms.putAll(getgoods_descExampleParms(example));
        parms.putAll(getgoods_priceExampleParms(example));
        parms.putAll(getpromote_priceExampleParms(example));
        parms.putAll(getcreate_timeExampleParms(example));
        parms.putAll(getgoods_colorExampleParms(example));
        parms.putAll(getgoods_sizeExampleParms(example));
        parms.putAll(getflagExampleParms(example));
        return parms;
    }
}