package com.shop.web.dao;

import com.shop.web.entity.Orders;
import com.shop.web.entity.OrdersExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrdersDAOImpl extends SqlMapClientDaoSupport implements OrdersDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public OrdersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public void insert(Orders record) {
        getSqlMapClientTemplate().insert("orders.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int updateByPrimaryKey(Orders record) {
        int rows = getSqlMapClientTemplate().update("orders.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int updateByPrimaryKeySelective(Orders record) {
        int rows = getSqlMapClientTemplate().update("orders.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public List selectByExample(OrdersExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("orders.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public List selectByExample(OrdersExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public Orders selectByPrimaryKey(Long id) {
        Orders key = new Orders();
        key.setId(id);
        Orders record = (Orders) getSqlMapClientTemplate().queryForObject("orders.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int deleteByExample(OrdersExample example) {
        int rows = getSqlMapClientTemplate().delete("orders.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        Orders key = new Orders();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("orders.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getIdExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NULL", "Y");
            } else {
                parms.put("AND_Id_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_NULL", "Y");
            } else {
                parms.put("AND_Id_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_EQUALS", "Y");
            } else {
                parms.put("AND_Id_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_Id_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GT", "Y");
            } else {
                parms.put("AND_Id_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_GE", "Y");
            } else {
                parms.put("AND_Id_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LT", "Y");
            } else {
                parms.put("AND_Id_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_Id_LE", "Y");
            } else {
                parms.put("AND_Id_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getorder_idExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getOrderId_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_NULL", "Y");
            } else {
                parms.put("AND_order_id_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_NOT_NULL", "Y");
            } else {
                parms.put("AND_order_id_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_EQUALS", "Y");
            } else {
                parms.put("AND_order_id_EQUALS", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_order_id_NOT_EQUALS", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_GT", "Y");
            } else {
                parms.put("AND_order_id_GT", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_GE", "Y");
            } else {
                parms.put("AND_order_id_GE", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_LT", "Y");
            } else {
                parms.put("AND_order_id_LT", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_LE", "Y");
            } else {
                parms.put("AND_order_id_LE", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        case OrdersExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_id_LIKE", "Y");
            } else {
                parms.put("AND_order_id_LIKE", "Y");
            }
            parms.put("orderId", example.getOrderId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getorder_statusExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getOrderStatus_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_NULL", "Y");
            } else {
                parms.put("AND_order_status_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_NOT_NULL", "Y");
            } else {
                parms.put("AND_order_status_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_EQUALS", "Y");
            } else {
                parms.put("AND_order_status_EQUALS", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_order_status_NOT_EQUALS", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_GT", "Y");
            } else {
                parms.put("AND_order_status_GT", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_GE", "Y");
            } else {
                parms.put("AND_order_status_GE", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_LT", "Y");
            } else {
                parms.put("AND_order_status_LT", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_LE", "Y");
            } else {
                parms.put("AND_order_status_LE", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        case OrdersExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_status_LIKE", "Y");
            } else {
                parms.put("AND_order_status_LIKE", "Y");
            }
            parms.put("orderStatus", example.getOrderStatus());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getuseridExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getUserid_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_NULL", "Y");
            } else {
                parms.put("AND_userid_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_NOT_NULL", "Y");
            } else {
                parms.put("AND_userid_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_EQUALS", "Y");
            } else {
                parms.put("AND_userid_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_userid_NOT_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_GT", "Y");
            } else {
                parms.put("AND_userid_GT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_GE", "Y");
            } else {
                parms.put("AND_userid_GE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_LT", "Y");
            } else {
                parms.put("AND_userid_LT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userid_LE", "Y");
            } else {
                parms.put("AND_userid_LE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getaddressExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getAddress_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_NULL", "Y");
            } else {
                parms.put("AND_address_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_NOT_NULL", "Y");
            } else {
                parms.put("AND_address_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_EQUALS", "Y");
            } else {
                parms.put("AND_address_EQUALS", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_address_NOT_EQUALS", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_GT", "Y");
            } else {
                parms.put("AND_address_GT", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_GE", "Y");
            } else {
                parms.put("AND_address_GE", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_LT", "Y");
            } else {
                parms.put("AND_address_LT", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_LE", "Y");
            } else {
                parms.put("AND_address_LE", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        case OrdersExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_address_LIKE", "Y");
            } else {
                parms.put("AND_address_LIKE", "Y");
            }
            parms.put("address", example.getAddress());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map gettelphoneExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getTelphone_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_NULL", "Y");
            } else {
                parms.put("AND_telphone_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_NOT_NULL", "Y");
            } else {
                parms.put("AND_telphone_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_EQUALS", "Y");
            } else {
                parms.put("AND_telphone_EQUALS", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_telphone_NOT_EQUALS", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_GT", "Y");
            } else {
                parms.put("AND_telphone_GT", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_GE", "Y");
            } else {
                parms.put("AND_telphone_GE", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_LT", "Y");
            } else {
                parms.put("AND_telphone_LT", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_LE", "Y");
            } else {
                parms.put("AND_telphone_LE", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        case OrdersExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_telphone_LIKE", "Y");
            } else {
                parms.put("AND_telphone_LIKE", "Y");
            }
            parms.put("telphone", example.getTelphone());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getpay_timeExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getPayTime_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_NULL", "Y");
            } else {
                parms.put("AND_pay_time_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_NOT_NULL", "Y");
            } else {
                parms.put("AND_pay_time_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_EQUALS", "Y");
            } else {
                parms.put("AND_pay_time_EQUALS", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_pay_time_NOT_EQUALS", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_GT", "Y");
            } else {
                parms.put("AND_pay_time_GT", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_GE", "Y");
            } else {
                parms.put("AND_pay_time_GE", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_LT", "Y");
            } else {
                parms.put("AND_pay_time_LT", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_pay_time_LE", "Y");
            } else {
                parms.put("AND_pay_time_LE", "Y");
            }
            parms.put("payTime", example.getPayTime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getemailExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getEmail_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_NULL", "Y");
            } else {
                parms.put("AND_email_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_NOT_NULL", "Y");
            } else {
                parms.put("AND_email_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_EQUALS", "Y");
            } else {
                parms.put("AND_email_EQUALS", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_email_NOT_EQUALS", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_GT", "Y");
            } else {
                parms.put("AND_email_GT", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_GE", "Y");
            } else {
                parms.put("AND_email_GE", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_LT", "Y");
            } else {
                parms.put("AND_email_LT", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_LE", "Y");
            } else {
                parms.put("AND_email_LE", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        case OrdersExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_email_LIKE", "Y");
            } else {
                parms.put("AND_email_LIKE", "Y");
            }
            parms.put("email", example.getEmail());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getorder_goodsExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getOrderGoods_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_NULL", "Y");
            } else {
                parms.put("AND_order_goods_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_NOT_NULL", "Y");
            } else {
                parms.put("AND_order_goods_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_EQUALS", "Y");
            } else {
                parms.put("AND_order_goods_EQUALS", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_order_goods_NOT_EQUALS", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_GT", "Y");
            } else {
                parms.put("AND_order_goods_GT", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_GE", "Y");
            } else {
                parms.put("AND_order_goods_GE", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_LT", "Y");
            } else {
                parms.put("AND_order_goods_LT", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_order_goods_LE", "Y");
            } else {
                parms.put("AND_order_goods_LE", "Y");
            }
            parms.put("orderGoods", example.getOrderGoods());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getflagExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        switch (example.getFlag_Indicator()) {
        case OrdersExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NULL", "Y");
            } else {
                parms.put("AND_flag_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NOT_NULL", "Y");
            } else {
                parms.put("AND_flag_NOT_NULL", "Y");
            }
            break;
        case OrdersExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_EQUALS", "Y");
            } else {
                parms.put("AND_flag_EQUALS", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrdersExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_flag_NOT_EQUALS", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_GT", "Y");
            } else {
                parms.put("AND_flag_GT", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrdersExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_GE", "Y");
            } else {
                parms.put("AND_flag_GE", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_LT", "Y");
            } else {
                parms.put("AND_flag_LT", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        case OrdersExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_flag_LE", "Y");
            } else {
                parms.put("AND_flag_LE", "Y");
            }
            parms.put("flag", example.getFlag());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    private Map getExampleParms(OrdersExample example) {
        Map parms = new HashMap();
        parms.putAll(getIdExampleParms(example));
        parms.putAll(getorder_idExampleParms(example));
        parms.putAll(getorder_statusExampleParms(example));
        parms.putAll(getuseridExampleParms(example));
        parms.putAll(getaddressExampleParms(example));
        parms.putAll(gettelphoneExampleParms(example));
        parms.putAll(getpay_timeExampleParms(example));
        parms.putAll(getemailExampleParms(example));
        parms.putAll(getorder_goodsExampleParms(example));
        parms.putAll(getflagExampleParms(example));
        return parms;
    }
}