package com.shop.web.dao;

import com.shop.web.entity.Orders;
import com.shop.web.entity.OrdersExample;
import java.util.List;

public interface OrdersDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    void insert(Orders record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    int updateByPrimaryKey(Orders record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    List selectByExample(OrdersExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    List selectByExample(OrdersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    Orders selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table orders
     *
     * @abatorgenerated Sat Jan 21 06:35:31 CST 2012
     */
    int deleteByPrimaryKey(Long id);
}