package com.shop.web.dao;

import com.shop.web.entity.UserAddress;
import com.shop.web.entity.UserAddressExample;
import java.util.List;

public interface UserAddressDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    void insert(UserAddress record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    int updateByPrimaryKey(UserAddress record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    int updateByPrimaryKeySelective(UserAddress record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    List selectByExample(UserAddressExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    List selectByExample(UserAddressExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    UserAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    int deleteByExample(UserAddressExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_address
     *
     * @abatorgenerated Thu Dec 29 12:26:31 CST 2011
     */
    int deleteByPrimaryKey(Integer id);
}