package com.shop.web.dao;

import com.shop.web.entity.User;
import com.shop.web.entity.UserExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public void insert(User record) {
        getSqlMapClientTemplate().insert("user.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("user.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("user.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public List selectByExample(UserExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("user.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public List selectByExample(UserExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public User selectByPrimaryKey(Integer id) {
        User key = new User();
        key.setId(id);
        User record = (User) getSqlMapClientTemplate().queryForObject("user.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int deleteByExample(UserExample example) {
        int rows = getSqlMapClientTemplate().delete("user.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        User key = new User();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getidExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_NULL", "Y");
            } else {
                parms.put("AND_id_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_NOT_NULL", "Y");
            } else {
                parms.put("AND_id_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_EQUALS", "Y");
            } else {
                parms.put("AND_id_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_id_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_GT", "Y");
            } else {
                parms.put("AND_id_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_GE", "Y");
            } else {
                parms.put("AND_id_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_LT", "Y");
            } else {
                parms.put("AND_id_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_id_LE", "Y");
            } else {
                parms.put("AND_id_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getuser_nameExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getUserName_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_NULL", "Y");
            } else {
                parms.put("AND_user_name_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_NOT_NULL", "Y");
            } else {
                parms.put("AND_user_name_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_EQUALS", "Y");
            } else {
                parms.put("AND_user_name_EQUALS", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_user_name_NOT_EQUALS", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_GT", "Y");
            } else {
                parms.put("AND_user_name_GT", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_GE", "Y");
            } else {
                parms.put("AND_user_name_GE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_LT", "Y");
            } else {
                parms.put("AND_user_name_LT", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_LE", "Y");
            } else {
                parms.put("AND_user_name_LE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_user_name_LIKE", "Y");
            } else {
                parms.put("AND_user_name_LIKE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getpasswordExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getPassword_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NULL", "Y");
            } else {
                parms.put("AND_password_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NOT_NULL", "Y");
            } else {
                parms.put("AND_password_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_EQUALS", "Y");
            } else {
                parms.put("AND_password_EQUALS", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_password_NOT_EQUALS", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_GT", "Y");
            } else {
                parms.put("AND_password_GT", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_GE", "Y");
            } else {
                parms.put("AND_password_GE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LT", "Y");
            } else {
                parms.put("AND_password_LT", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LE", "Y");
            } else {
                parms.put("AND_password_LE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LIKE", "Y");
            } else {
                parms.put("AND_password_LIKE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getlogin_timeExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getLoginTime_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_NULL", "Y");
            } else {
                parms.put("AND_login_time_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_NOT_NULL", "Y");
            } else {
                parms.put("AND_login_time_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_EQUALS", "Y");
            } else {
                parms.put("AND_login_time_EQUALS", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_login_time_NOT_EQUALS", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_GT", "Y");
            } else {
                parms.put("AND_login_time_GT", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_GE", "Y");
            } else {
                parms.put("AND_login_time_GE", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_LT", "Y");
            } else {
                parms.put("AND_login_time_LT", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_login_time_LE", "Y");
            } else {
                parms.put("AND_login_time_LE", "Y");
            }
            parms.put("loginTime", example.getLoginTime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getsysflagExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getSysflag_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_NULL", "Y");
            } else {
                parms.put("AND_sysflag_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_sysflag_NOT_EQUALS", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GT", "Y");
            } else {
                parms.put("AND_sysflag_GT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_GE", "Y");
            } else {
                parms.put("AND_sysflag_GE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LT", "Y");
            } else {
                parms.put("AND_sysflag_LT", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_sysflag_LE", "Y");
            } else {
                parms.put("AND_sysflag_LE", "Y");
            }
            parms.put("sysflag", example.getSysflag());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sat Dec 17 22:21:48 CST 2011
     */
    private Map getExampleParms(UserExample example) {
        Map parms = new HashMap();
        parms.putAll(getidExampleParms(example));
        parms.putAll(getuser_nameExampleParms(example));
        parms.putAll(getpasswordExampleParms(example));
        parms.putAll(getlogin_timeExampleParms(example));
        parms.putAll(getsysflagExampleParms(example));
        return parms;
    }
}